version: "3.1"
services:
  jenkins:
    container_name: "jenkins"
    image: "jembim/bootcamp-jenkins:0.1"
    restart: always
    privileged: true
    networks:
      - dockernetwork
    ports:
      - "8080:8080"
      - "50000:50000"
    secrets:
      - jenkins-user
      - jenkins-pass

  jfrog:
    container_name: artifactory
    image: "docker.bintray.io/jfrog/artifactory-cpp-ce:latest"
    restart: always
    networks:
      - dockernetwork
    ports:
      - "8081:8081"

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - dockernetwork
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonar-db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonar-db:
    image: postgres
    networks:
      - dockernetwork
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  dockernetwork:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:

secrets:
  jenkins-user:
    file: ./secrets/user.txt
  jenkins-pass:
    file: ./secrets/password.txt
