version: "3.1"
services:
  jenkins:
    container_name: "jenkins"
    image: "jembim/jenkins-poc:0.1"
    restart: always
    privileged: true
    networks:
      - dockernetwork
    ports:
      - "8080:8080"
      - "50000:50000"
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - jenkins_home:/var/jenkins_home 

  jfrog:
    container_name: artifactory
    image: "docker.bintray.io/jfrog/artifactory-cpp-ce:latest"
    restart: always
    networks:
      - dockernetwork
    ports:
      - "8081:8081"
    volumes:
      - artifactory_data:/artifactory_data

  sonarqube:
    image: sonarqube:latest
    ports:
      - "8082:9000"
    networks:
      - dockernetwork
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonar-db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonar-db:
    image: postgres
    networks:
      - dockernetwork
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:latest
    restart: always
    networks:
      - dockernetwork
    expose:
      - "4444"
    ports:
      - "4444:4444"

  selenium-node-chrome:
    container_name: selenium-node-chrome
    image: selenium/node-chrome:latest
    restart: always
    networks:
      - dockernetwork
    environment:
      SE_OPTS: "-nodeConfig /var/selenium-config/config-chrome.json"
      REMOTE_HOST: "http://selenium-node-chrome:5555"
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"

  selenium-node-firefox:
    container_name: selenium-node-firefox
    image: selenium/node-firefox:latest
    restart: always
    networks:
      - dockernetwork
    environment:
      SE_OPTS: "-nodeConfig /var/selenium-config/config-firefox.json"
      REMOTE_HOST: "http://selenium-node-firefox:5555"
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"

networks:
  dockernetwork:

volumes:
  jenkins_home:
  artifactory_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:

secrets:
  jenkins-user:
    file: ./secrets/user.txt
  jenkins-pass:
    file: ./secrets/password.txt
